name: build

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry==1.1.4
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run tests
        run: poetry run pytest
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.repository_owner == 'bjoluc' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        run: pip install poetry==1.1.4
      - uses: bjoluc/semantic-release-config-poetry@v1
        with:
          repository: https://test.pypi.org/legacy/
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
